### ISSUE TITLE
Fare sumout solo delle hidden variable in eliminationAsk 

### ISSUE THREAD

**Issue by giatorta** [lamba92/bayesian-net-project#1]
Nel ciclo for di `eliminationAsk` viene fatto il sumout di tutte le variabili di cui sono comparsi i fattori che le contengono (lista `toBeCompacted`).

In realtà, tra le variabili `toBeCompacted` va fatto il sumout solo di quelle hidden, quindi nel ciclo sulle variabili `toBeCompacted` va sempre controllato se `hidden.contains(rv)` prima di fare il `sumout` (oppure le non-hidden non vanno neanche aggiunte a `toBeCompacted`)

**Comment by lamba92** [comment]
Grazie per la segnalazione! Lo risolvo tra poco!

**Comment by lamba92** [comment]
Nell'ultimo [commit](https://github.com/lamba92/bayesian-net-project/commit/e2a8cca21196b6b64fac4c0a8b776b3360787627) ho modificato il codice come suggerito, questa volta `CustomEliminationAsk()` funziona sulle reti costruite da aima, ma non sulle nostre, che siano costruite a mano che parsate. Continuo ad indagare ma non riesco a trovare il motivo.
